# Generated by Django 2.2 on 2021-05-13 18:18

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, unique=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 13, 23, 48, 24, 913154))),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color_changed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcolor', to='shop.Color')),
            ],
            options={
                'verbose_name_plural': 'color',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 13, 23, 48, 24, 913154))),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='size_changed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'size',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('item_detail', models.TextField(blank=True, null=True, verbose_name='Product Details')),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('productimage', models.ImageField(upload_to='images/product/')),
                ('expected_delivery_date', models.IntegerField(blank=True, null=True, verbose_name='Expected Delivery Days')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 13, 23, 48, 24, 913154))),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='age_changed_by', to=settings.AUTH_USER_MODEL)),
                ('color_ids', models.ManyToManyField(blank=True, to='shop.Color')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('relative_product_ids', models.ManyToManyField(blank=True, related_name='_product_relative_product_ids_+', to='shop.Product', verbose_name='Related Product')),
                ('size_ids', models.ManyToManyField(to='shop.Size')),
            ],
            options={
                'verbose_name_plural': 'product',
            },
        ),
    ]
