# Generated by Django 3.2.3 on 2021-05-13 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 14, 0, 4, 11, 589609)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 14, 0, 4, 11, 590614)),
        ),
        migrations.AlterField(
            model_name='size',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 14, 0, 4, 11, 589609)),
        ),
    ]
