# Generated by Django 3.2.3 on 2021-05-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210514_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='edit_date',
            new_name='write_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='edit_date',
            new_name='write_date',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='edit_date',
            new_name='write_date',
        ),
        migrations.AlterField(
            model_name='color',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
