# Generated by Django 3.2.3 on 2021-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210514_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='careinstructions',
            name='details',
            field=models.CharField(default='CI', max_length=250),
        ),
    ]
