# Generated by Django 3.2.3 on 2021-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_usercart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='color_id',
        ),
        migrations.AlterField(
            model_name='usercart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
    ]
