# Generated by Django 3.2.3 on 2021-05-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210514_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='size',
            new_name='size_id',
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='usercart',
            name='color_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.color', verbose_name='Color of Product'),
        ),
    ]
